#!/bin/bash

while 1; do
# wait for connection
while ! ping -q -t 5 -w1 -c1 192.168.1.100; do
	echo "No connection"
	sleep 1
done

# now we are connected
# ...start your script!

cd /home/pi/projects/WOT-Demo/Raspberry1
./main_lcd
done
